framework:
    default_locale: fr
    enabled_locales: ['fr', 'bg', 'cs', 'da', 'de', 'el', 'en', 'et', 'fi', 'ga', 'hr', 'hu', 'it', 'lt', 'lv', 'mt', 'nl', 'pl', 'pt', 'ro', 'sk', 'sl', 'es', 'sv']
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: ['fr']
        providers:
