<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260404145403 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create users, works, civitalisme updates, contact messages and messenger transport tables.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE contact_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, email VARCHAR(180) NOT NULL, company VARCHAR(120) DEFAULT NULL, subject VARCHAR(180) NOT NULL, message TEXT NOT NULL, is_read BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE project_update (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, audience VARCHAR(255) NOT NULL, title VARCHAR(180) NOT NULL, summary TEXT NOT NULL, body TEXT NOT NULL, status_label VARCHAR(100) NOT NULL, outcome VARCHAR(255) DEFAULT NULL, cta_label VARCHAR(80) DEFAULT NULL, cta_url VARCHAR(255) DEFAULT NULL, is_featured BOOLEAN DEFAULT false NOT NULL, sort_order INT DEFAULT 0 NOT NULL, is_published BOOLEAN DEFAULT true NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE work (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(180) NOT NULL, client_name VARCHAR(120) DEFAULT NULL, role_label VARCHAR(120) DEFAULT NULL, excerpt TEXT NOT NULL, description TEXT NOT NULL, stack_summary VARCHAR(255) NOT NULL, project_url VARCHAR(255) DEFAULT NULL, repository_url VARCHAR(255) DEFAULT NULL, image_path VARCHAR(255) DEFAULT NULL, is_featured BOOLEAN DEFAULT false NOT NULL, sort_order INT DEFAULT 0 NOT NULL, is_published BOOLEAN DEFAULT true NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE contact_message');
        $this->addSql('DROP TABLE project_update');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE work');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
