<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260412152527 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add about-page entities (experiences, trainings, testimonials, profile links) and tools_used on work.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE experience (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, company VARCHAR(100) NOT NULL, role VARCHAR(100) NOT NULL, period VARCHAR(50) NOT NULL, location VARCHAR(80) DEFAULT NULL, status VARCHAR(80) DEFAULT NULL, theme VARCHAR(30) NOT NULL, logo_path VARCHAR(255) DEFAULT NULL, logo_monogram VARCHAR(10) DEFAULT NULL, summary TEXT NOT NULL, sort_order INT DEFAULT 0 NOT NULL, is_published BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE profile_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category VARCHAR(30) NOT NULL, title VARCHAR(100) NOT NULL, url VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, badge VARCHAR(10) DEFAULT NULL, theme VARCHAR(30) NOT NULL, year VARCHAR(10) DEFAULT NULL, sort_order INT DEFAULT 0 NOT NULL, is_published BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE testimonial (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, author_name VARCHAR(100) NOT NULL, author_role VARCHAR(100) DEFAULT NULL, company VARCHAR(100) DEFAULT NULL, quote TEXT NOT NULL, theme VARCHAR(30) DEFAULT NULL, sort_order INT DEFAULT 0 NOT NULL, is_published BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE training (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, school VARCHAR(100) NOT NULL, program VARCHAR(150) NOT NULL, period VARCHAR(20) NOT NULL, theme VARCHAR(30) NOT NULL, image_path VARCHAR(255) DEFAULT NULL, summary TEXT NOT NULL, sort_order INT DEFAULT 0 NOT NULL, is_published BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE work ADD tools_used VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE experience');
        $this->addSql('DROP TABLE profile_link');
        $this->addSql('DROP TABLE testimonial');
        $this->addSql('DROP TABLE training');
        $this->addSql('ALTER TABLE work DROP tools_used');
    }
}
